"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "./scenes/global/Sidebar";
import Topbar from "./scenes/global/Topbar";
import { ColorModeContext, useMode } from "./theme";
import { CssBaseline, ThemeProvider } from "@mui/material";
import { useState } from "react";
import App from "./Provider";
import Layout from "./scenes/layout/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FrontEnd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
